<?php

namespace Database\Seeders;

use App\Models\JobPosting;
use App\Models\JobCategory;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class JobPostingSeeder extends Seeder
{
    public function run(): void
    {
        $employers = User::whereHas('role', function($q) {
            $q->where('slug', 'employer');
        })->get();

        if ($employers->isEmpty()) {
            return;
        }

        $jobs = [
            [
                'title' => 'Senior Software Engineer',
                'category' => 'IT & Technology',
                'description' => 'We are looking for an experienced Senior Software Engineer to join our dynamic team. You will be responsible for designing, developing, and maintaining web applications using modern technologies.',
                'requirements' => 'Bachelor\'s degree in Computer Science or related field. 5+ years of experience in software development. Strong proficiency in Laravel, PHP, JavaScript, and MySQL. Experience with RESTful APIs and version control systems.',
                'responsibilities' => 'Design and develop scalable web applications. Write clean, maintainable code. Collaborate with cross-functional teams. Mentor junior developers. Participate in code reviews.',
                'employment_type' => 'full-time',
                'experience_years' => '5-7 years',
                'education_level' => 'Bachelor\'s Degree',
                'salary_min' => '15000',
                'salary_max' => '20000',
                'salary_period' => 'monthly',
                'location_city' => 'Dubai',
                'priority' => 'premium',
                'skills' => ['Laravel', 'PHP', 'JavaScript', 'MySQL', 'Git'],
            ],
            [
                'title' => 'Digital Marketing Manager',
                'category' => 'Sales & Marketing',
                'description' => 'Join our marketing team as a Digital Marketing Manager. Lead digital campaigns, manage social media, and drive online growth.',
                'requirements' => 'Bachelor\'s degree in Marketing or related field. 4+ years of digital marketing experience. Expertise in SEO, SEM, social media marketing, and analytics tools.',
                'responsibilities' => 'Develop and execute digital marketing strategies. Manage social media accounts. Analyze campaign performance. Lead marketing team. Budget management.',
                'employment_type' => 'full-time',
                'experience_years' => '4-6 years',
                'education_level' => 'Bachelor\'s Degree',
                'salary_min' => '12000',
                'salary_max' => '16000',
                'salary_period' => 'monthly',
                'location_city' => 'Abu Dhabi',
                'priority' => 'premium',
                'skills' => ['SEO', 'SEM', 'Social Media', 'Google Analytics', 'Content Marketing'],
            ],
            [
                'title' => 'Senior UI/UX Designer',
                'category' => 'IT & Technology',
                'description' => 'We are seeking a talented UI/UX Designer to create beautiful and functional user interfaces for our digital products.',
                'requirements' => 'Portfolio demonstrating UI/UX design skills. 3+ years of experience. Proficiency in Figma, Adobe XD, and Sketch. Understanding of user-centered design principles.',
                'responsibilities' => 'Design user interfaces for web and mobile applications. Create wireframes and prototypes. Conduct user research. Collaborate with developers. Maintain design systems.',
                'employment_type' => 'full-time',
                'experience_years' => '3-5 years',
                'education_level' => 'Bachelor\'s Degree',
                'salary_min' => '11000',
                'salary_max' => '15000',
                'salary_period' => 'monthly',
                'location_city' => 'Dubai',
                'priority' => 'premium',
                'skills' => ['UI Design', 'UX Design', 'Figma', 'Adobe XD', 'Prototyping'],
            ],
            [
                'title' => 'Accountant',
                'category' => 'Finance & Accounting',
                'description' => 'Looking for a detail-oriented Accountant to manage financial records, prepare reports, and ensure compliance.',
                'requirements' => 'Bachelor\'s degree in Accounting. 3+ years of experience. Knowledge of UAE tax laws. Proficiency in accounting software.',
                'responsibilities' => 'Maintain financial records. Prepare monthly reports. Handle accounts payable/receivable. Ensure tax compliance. Assist in audits.',
                'employment_type' => 'full-time',
                'experience_years' => '3-5 years',
                'education_level' => 'Bachelor\'s Degree',
                'salary_min' => '8000',
                'salary_max' => '12000',
                'salary_period' => 'monthly',
                'location_city' => 'Abu Dhabi',
                'priority' => 'normal',
                'skills' => ['Accounting', 'Taxation', 'Financial Reporting', 'QuickBooks', 'Excel'],
            ],
            [
                'title' => 'HR Manager',
                'category' => 'Human Resources',
                'description' => 'Seeking an experienced HR Manager to oversee all aspects of human resources practices and processes.',
                'requirements' => 'Bachelor\'s degree in HR or related field. 5+ years of HR experience. Strong knowledge of UAE labor laws. Excellent communication skills.',
                'responsibilities' => 'Manage recruitment process. Handle employee relations. Develop HR policies. Oversee performance management. Ensure legal compliance.',
                'employment_type' => 'full-time',
                'experience_years' => '5-7 years',
                'education_level' => 'Bachelor\'s Degree',
                'salary_min' => '14000',
                'salary_max' => '18000',
                'salary_period' => 'monthly',
                'location_city' => 'Dubai',
                'priority' => 'premium',
                'skills' => ['Recruitment', 'Employee Relations', 'HR Policies', 'Performance Management'],
            ],
            [
                'title' => 'Content Writer',
                'category' => 'Sales & Marketing',
                'description' => 'Creative content writer needed to produce engaging content for websites, blogs, and social media.',
                'requirements' => 'Bachelor\'s degree in English, Journalism, or related field. 2+ years of content writing experience. Excellent writing and editing skills.',
                'responsibilities' => 'Write blog posts and articles. Create social media content. Edit and proofread content. Research industry topics. Optimize content for SEO.',
                'employment_type' => 'full-time',
                'experience_years' => '2-4 years',
                'education_level' => 'Bachelor\'s Degree',
                'salary_min' => '6000',
                'salary_max' => '9000',
                'salary_period' => 'monthly',
                'location_city' => 'Dubai',
                'priority' => 'normal',
                'skills' => ['Content Writing', 'Copywriting', 'SEO', 'Social Media', 'Editing'],
            ],
            [
                'title' => 'Sales Executive',
                'category' => 'Sales & Marketing',
                'description' => 'Dynamic sales executive needed to drive business growth through client acquisition and relationship management.',
                'requirements' => 'Bachelor\'s degree. 2+ years of sales experience. Valid UAE driving license. Excellent communication skills.',
                'responsibilities' => 'Generate new leads. Meet sales targets. Maintain client relationships. Prepare sales reports. Conduct product presentations.',
                'employment_type' => 'full-time',
                'experience_years' => '2-4 years',
                'education_level' => 'Bachelor\'s Degree',
                'salary_min' => '8000',
                'salary_max' => '12000',
                'salary_period' => 'monthly',
                'location_city' => 'Abu Dhabi',
                'priority' => 'normal',
                'skills' => ['Sales', 'Negotiation', 'Client Relations', 'Communication', 'CRM'],
            ],
            [
                'title' => 'Civil Engineer',
                'category' => 'Engineering',
                'description' => 'Experienced Civil Engineer required for construction projects. Must have strong technical knowledge and site experience.',
                'requirements' => 'Bachelor\'s degree in Civil Engineering. 4+ years of UAE experience. Knowledge of local building codes. AutoCAD proficiency.',
                'responsibilities' => 'Oversee construction projects. Prepare technical drawings. Ensure quality standards. Coordinate with contractors. Site supervision.',
                'employment_type' => 'full-time',
                'experience_years' => '4-6 years',
                'education_level' => 'Bachelor\'s Degree',
                'salary_min' => '10000',
                'salary_max' => '14000',
                'salary_period' => 'monthly',
                'location_city' => 'Sharjah',
                'priority' => 'premium',
                'skills' => ['Civil Engineering', 'AutoCAD', 'Project Management', 'Construction'],
            ],
            [
                'title' => 'Registered Nurse',
                'category' => 'Healthcare & Medical',
                'description' => 'Compassionate and skilled Registered Nurse needed for our healthcare facility. Provide quality patient care.',
                'requirements' => 'Bachelor\'s degree in Nursing. Valid DHA/MOH license. 3+ years of clinical experience. Excellent patient care skills.',
                'responsibilities' => 'Provide patient care. Administer medications. Monitor patient vitals. Maintain medical records. Collaborate with doctors.',
                'employment_type' => 'full-time',
                'experience_years' => '3-5 years',
                'education_level' => 'Bachelor\'s Degree',
                'salary_min' => '9000',
                'salary_max' => '13000',
                'salary_period' => 'monthly',
                'location_city' => 'Dubai',
                'priority' => 'premium',
                'skills' => ['Patient Care', 'Medical Procedures', 'EMR Systems', 'Critical Care'],
            ],
            [
                'title' => 'Customer Service Representative',
                'category' => 'Customer Service',
                'description' => 'Join our customer service team to provide excellent support to our clients.',
                'requirements' => 'High school diploma or equivalent. 1-2 years of customer service experience. Fluent in English and Arabic. Strong communication skills.',
                'responsibilities' => 'Handle customer inquiries. Resolve complaints. Process orders. Maintain customer records. Provide product information.',
                'employment_type' => 'full-time',
                'experience_years' => '1-2 years',
                'education_level' => 'High School',
                'salary_min' => '4000',
                'salary_max' => '6000',
                'salary_period' => 'monthly',
                'location_city' => 'Dubai',
                'priority' => 'normal',
                'skills' => ['Customer Service', 'Communication', 'Problem Solving', 'CRM Software'],
            ],
            [
                'title' => 'Web Developer',
                'category' => 'IT & Technology',
                'description' => 'Talented web developer needed to build and maintain modern web applications.',
                'requirements' => 'Bachelor\'s degree in Computer Science. 2+ years of web development experience. Strong HTML, CSS, JavaScript skills. Experience with modern frameworks.',
                'responsibilities' => 'Develop responsive websites. Write clean code. Debug and troubleshoot. Collaborate with designers. Optimize performance.',
                'employment_type' => 'full-time',
                'experience_years' => '2-4 years',
                'education_level' => 'Bachelor\'s Degree',
                'salary_min' => '9000',
                'salary_max' => '13000',
                'salary_period' => 'monthly',
                'location_city' => 'Dubai',
                'priority' => 'normal',
                'skills' => ['HTML', 'CSS', 'JavaScript', 'React', 'PHP'],
            ],
            [
                'title' => 'Travel & Tourism Coordinator',
                'category' => 'Travel & Tourism / Leisure',
                'description' => 'Join our tourism team to coordinate travel packages and ensure excellent customer experiences.',
                'requirements' => 'Bachelor\'s degree in Tourism or related field. 2+ years in tourism industry. Knowledge of UAE tourist attractions. Multilingual preferred.',
                'responsibilities' => 'Coordinate travel packages. Handle bookings. Provide tourist information. Organize tours. Manage customer queries.',
                'employment_type' => 'full-time',
                'experience_years' => '2-3 years',
                'education_level' => 'Bachelor\'s Degree',
                'salary_min' => '6000',
                'salary_max' => '9000',
                'salary_period' => 'monthly',
                'location_city' => 'Abu Dhabi',
                'priority' => 'normal',
                'skills' => ['Tourism', 'Customer Service', 'Booking Systems', 'Languages'],
            ],
            [
                'title' => 'Data Analyst',
                'category' => 'IT & Technology',
                'description' => 'Data analyst required to transform data into actionable insights for business decisions.',
                'requirements' => 'Bachelor\'s degree in Statistics, Mathematics, or related field. 3+ years of data analysis experience. Proficiency in SQL, Python, and data visualization tools.',
                'responsibilities' => 'Analyze complex datasets. Create reports and dashboards. Identify trends. Present findings. Support data-driven decisions.',
                'employment_type' => 'full-time',
                'experience_years' => '3-5 years',
                'education_level' => 'Bachelor\'s Degree',
                'salary_min' => '12000',
                'salary_max' => '16000',
                'salary_period' => 'monthly',
                'location_city' => 'Dubai',
                'priority' => 'premium',
                'skills' => ['Data Analysis', 'SQL', 'Python', 'Tableau', 'Excel'],
            ],
        ];

        foreach ($jobs as $index => $jobData) {
            $employer = $employers->random();
            $category = JobCategory::where('name', $jobData['category'])->first();

            JobPosting::create([
                'employer_id' => $employer->id,
                'category_id' => $category?->id,
                'title' => $jobData['title'],
                'slug' => Str::slug($jobData['title']) . '-' . time() . '-' . $index,
                'description' => $jobData['description'],
                'requirements' => $jobData['requirements'],
                'responsibilities' => $jobData['responsibilities'],
                'employment_type' => $jobData['employment_type'],
                'experience_years' => $jobData['experience_years'],
                'education_level' => $jobData['education_level'],
                'salary_min' => $jobData['salary_min'],
                'salary_max' => $jobData['salary_max'],
                'salary_currency' => 'AED',
                'salary_period' => $jobData['salary_period'],
                'location_city' => $jobData['location_city'],
                'location_country' => 'UAE',
                'status' => 'published',
                'priority' => $jobData['priority'],
                'published_at' => now()->subDays(rand(1, 30)),
                'skills_required' => json_encode($jobData['skills']),
                'languages_required' => json_encode(['English']),
                'views_count' => rand(50, 500),
                'applications_count' => rand(0, 20),
            ]);
        }
    }
}



